
name: Build and test

on:
  pull_request:
    branches: [ MC17, fmpe-1.x ]
  push:
    branches: [ MC17, fmpe-1.x ]

jobs:
  build-and-test:
    uses: TeamBlackCrystal/GTNH-Actions-Workflows/.github/workflows/build-and-test.yml@master
    secrets: inherit
