
name: Release tagged build

on:
  push:
    tags: [ '*' ]

permissions:
  contents: write
env:
  MAVEN_PUBLISHING_URL: "https://nexus.teamblackcrystal.com/repository/maven-releases2/"

jobs:
  release-tags:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/release-tags.yml@master
    secrets: inherit
